# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Amit Pompas
title: Backend Developer
# email: amitpom14@gmail.com
# website: www.github.com/AmitIsMe

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  AmitIsMe
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: amit-pompas
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: Amit_is_me
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: gmail
  icon: fas fa-envelope
  url: mailto:amitpom14@gmail.com
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
# #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Amit and I'm a Motivated backend developer with a passion for secure, scalable, and user-friendly solutions.

  I am most skilled in: <mark>python</mark> and <mark>Eating Pizza</mark>

darkmode: true  # Adjust as needed (options: true, false, never)

content:

  - title: Technical Skills
    layout: text
    content: |
      **Programming Languages:** Python, Java, C, JavaScript  
      **Frameworks & Libraries:** Node.js, Django, Express, React, Material-UI, Pandas  
      **Databases & Tools:** MongoDB, MySQL, Redis, Git, Linux  
      **English Proficiency:** Fluent in speaking and writing  

  - title: Professional Projects
    layout: list
    content:
      - title: Anti-Phishing Chrome Extension
        sub_title: Backend & Security Project
        description: |
          - Developed a Chrome extension to detect phishing threats.
          - Built a scalable backend for SSL certificate validation using Node.js.
          - Created a responsive front-end interface for real-time detection.
          - Adapted quickly to evolving project requirements.

      - title: Secure Development Web Application
        sub_title: Full-Stack Web Application
        description: |
          - Built a secure web application with Django and MySQL.
          - Identified and mitigated security vulnerabilities by following industry standards.
          - Improved application reliability through secure coding practices.

  - title: Education
    layout: list
    content:
      - title: Holon Institute of Technology (HIT)
        sub_title: B.Sc. in Computer Science (2021 - 2024)
        description: |
          - Key coursework: Data Structures, Databases, Operating Systems, AI, and Machine Learning.
          - Gained practical experience with low-level computing, Linux, Python, and data analysis.

      - title: John Bryce Training
        sub_title: Full-Stack Java Development (2019 - 2020)
        description: |
          - Completed with honors for developing a robust "Coupon Management" web application.
          - Acquired expertise in Spring Boot, Hibernate, and MySQL.

  - title: Experience
    layout: list
    content:
      - title: Radio 103 FM
        sub_title: Radio Sound Technician (2018 - 2019)
        description: |
          - Ensured smooth live broadcasts in high-pressure environments.
          - Enhanced teamwork and communication skills by coordinating with technical staff and on-air talent.
          - Supervised broadcast operations and edited radio programs.

      - title: GLZ & GLGLZ Radio
        sub_title: Radio Sound Technician (Military Service, 2014 - 2017)
        description: |
          - Provided technical responsibility for live news broadcasts and field updates.
          - Collaborated with various teams and trained new employees on system operations.

  - title: Additional Strengths
    layout: text
    content: |
      - Quick learner with proven success in independently completing projects.
      - Strong analytical and critical thinking skills.
      - Passionate about working on meaningful projects in collaborative environments.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Producing music
      - Surfing
      - [Sharing my knowledge in a YouTube channel](https://youtube.com/@amit_is_me?si=TYBVro3xZetn0ZdN)

     
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
