# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Amit Pompas
title: Amit Pompas Resume
email: amitpom14@gmail.com
website: www.github.com/pompas-code

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Amit and I'm a Motivated backend developer with a passion for secure, scalable, and user-friendly solutions.

  I am most skilled in: <mark>python</mark> and <mark>Eating Pizza</mark>

darkmode: true  # Adjust as needed (options: true, false, never)

content:
  - title: Summary
    layout: text
    content: |
      Highly motivated backend developer with a strong foundation in computer science. Experienced in delivering secure, scalable, and user-friendly solutions. Quick learner with a passion for innovation and teamwork.

  - title: Technical Skills
    layout: list
    content:
      - title: Languages
        description: Python, Java, C, JavaScript
      - title: Frameworks & Libraries
        description: Node.js, Django, Express, React, Material-UI, Pandas
      - title: Databases & Tools
        description: MongoDB, MySQL, Redis, Git, Linux

  - title: Professional Projects
    layout: list
    content:
      - title: Anti-Phishing Chrome Extension
        description: |
          - Developed a Chrome extension for phishing threat detection and mitigation.
          - Designed a scalable backend for URL and SSL certificate management using Node.js.
          - Built a responsive frontend for real-time security monitoring.
      - title: Secure Development Web Application
        description: |
          - Created a full-stack web application with Django and MySQL.
          - Followed industry standards to secure against common vulnerabilities.
          - Improved application stability through secure coding practices.

  - title: Education
    layout: list
    content:
      - title: Holon Institute of Technology (HIT)
        sub_title: B.Sc. in Computer Science (2021 - 2024)
        content: |
          - Key Coursework: Data Structures, Databases, Operating Systems, AI & Machine Learning
          - Highlights: Applied C programming, built Linux systems, and utilized Python for data analysis.
      - title: John Bryce Training
        sub_title: Full-Stack Java Development (2019 - 2020)
        content: |
          - Completed with honors for a robust "Coupon Management" web application.
          - Developed expertise in Spring Boot, Hibernate, and MySQL.

  - title: Experience
    layout: list
    content:
      - title: Radio 103 FM
        sub_title: Radio Sound Technician (2018 - 2019)
        description: |
          - Collaborated under high-pressure environments to ensure smooth live broadcasts.
          - Developed real-time problem-solving skills and technical expertise.
      - title: Military Service - GLZ & GLGLZ Radio
        sub_title: Radio Sound Technician (2014 - 2017)
        description: |
          - Provided technical support for live news broadcasts and updates from the field.
          - Trained new employees in radio systems and operational processes.

  - title: Additional Strengths
    layout: text
    content: |
      - Strong analytical thinking, problem-solving, and teamwork skills.
      - Quick learner with a history of successfully completing independent projects.
      - Passionate about contributing to innovative, meaningful projects.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
